version: 2.1


jobs:
  test:
    docker:
      - image: cimg/openjdk:23.0.2
    steps:
      - checkout
      - run: java --version


workflows:
  test-deploy:
    jobs:
      - test
  schedule-workflow:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master

    jobs:
      - test
