version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/openjdk:23.0.2-maven
    steps:
      - checkout
      - run: 
          name: Install Dependencies
          command: sudo apt-get update && apt-get install -y maven
      - run: 
          name: Check Version
          command: mvn --version
      




