version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
     docker:
      - image: cimg/openjdk:23.0.2
     steps:
      - checkout
      - run: 
          name: Install Dependencies
          command: apt get install mvn
      - run:
          name: Check Version
          command: mvn --version




