version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: ubuntu-2004:2023.04.2
    steps:
      - checkout
      - run: 
          name: Install Dependencies
          command: sudo apt-get update && apt-get install -y maven
      - run: 
          name: Check Version
          command: mvn --version
      




