version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: openjdk:17
    steps:
      - checkout
      - run:
          name: Install Maven
          command: sudo apt-get update && sudo apt-get install -y maven
      - run:
          name: Check Maven Version
          command: mvn --version
