version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    jobs:
  build:
    docker:
      - image: cimg/openjdk:23.0.2
    steps:
      - checkout
      - run: java --version
